use_frameworks!

platform :ios, '8.0'

target 'PPSPrivateStaticLibrary_Example' do
  pod 'PPSPrivateStaticLibrary', :path => '../'

  target 'PPSPrivateStaticLibrary_Tests' do
    inherit! :search_paths

    
  end
end
